### ISSUE TITLE
String values in the toml file have inconsistent casing

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#50]
*This always bothered me in v4, and it is here again in v5 (at least it is only the values and not also the fields this time)*

The string values in the toml files have an inconsistent casing. Consider the following snippet from [VirxEC/python-interface/test/rlbot.toml](https://github.com/VirxEC/python-interface/blob/master/tests/rlbot.toml):

```toml
[rlbot]
launcher = "steam"
auto_start_bots = true

[match]
game_mode = "Soccer"
game_map_upk = "Stadium_P"
existing_match_behavior = "Restart"
enable_rendering = true

[mutators]
match_length = "Twenty_Minutes"
ball_max_speed = "Fast"
boost_strength = "OneAndAHalf"
respawn_time = "One_Second"

[[cars]]
team = 0
type = "psyonix"
skill = "pro"
```

The strings have a mix of PascalCase, lower case, and Snakey_Pascal_Case. This is ugly and makes it difficult to write toml files by hand.

Let's make the string value casing consistent. I vote for PascalCase or UPPER_SNAKE_CASE. Using lower snake_case for fields *and* values seems wrong imo.

Of course, strings like bot names and paths should not adhere to this casing convention, but all the framework constants should.
